### ISSUE TITLE
Why did I not find the Deconv2D layer in keras.layers ?

### ISSUE THREAD

**Issue by RenLuXi** [TachibanaYoshino/Road-Crack-Segmentation--Keras#3]
The error is as follows：
from keras.layers import Conv2D,MaxPooling2D,UpSampling2D,BatchNormalization,Reshape,Permute,Activation,Deconv2D,Concatenate,Input
ImportError: cannot import name 'Deconv2D'

sorry,I can't find  the Deconv2D layer in keras.layers,I did not find this on the official website of keras？Could you help me?thank you very much!

**Comment by imustwangxin** [comment]
I do n’t know if you will solve this problem now. I will replace from keras.layers import Deconv2D with from keras.layers.convolutional import Deconv2D. It solves the problem perfectly. Hope can help you

**Comment by RenLuXi** [comment]
> 我不知道你现在是否可以解决这个问题。我将从keras.layers.convolutional导入Deconv2D替换为从keras.layers导入Deconv2D。它完美地解决了这个问题。希望可以帮到你

You are right!Thank you.
